# Generated by Django 5.0.7 on 2024-07-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cat',
            field=models.CharField(default='Family', max_length=30),
        ),
    ]
