# Generated by Django 5.0.7 on 2024-07-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='cat',
        ),
        migrations.AddField(
            model_name='category',
            name='contacts',
            field=models.ManyToManyField(related_name='categories', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Office', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
