# Generated by Django 5.0.7 on 2024-07-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_category_category_remove_category_contact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Family', 'Family'), ('Friends', 'Friends'), ('Office', 'Office')], default='Office', max_length=100),
        ),
    ]
